import * as THREE from 'three'; import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const $=s=>document.querySelector(s),app=$('#app'),scene=new THREE.Scene();scene.background=new THREE.Color(0x78aebe);scene.fog=new THREE.FogExp2(0x86aeb3,.0031);
const camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.1,800);camera.position.set(92,64,126);const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;app.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,10,5);controls.enableDamping=true;controls.maxDistance=230;controls.minDistance=18;controls.maxPolarAngle=1.48;
scene.add(new THREE.HemisphereLight(0xd9f2ff,0x785331,2));const sun=new THREE.DirectionalLight(0xffd7a0,3.6);sun.position.set(-80,110,-40);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);
const M={sand:new THREE.MeshStandardMaterial({color:0xb68e5a,roughness:1}),road:new THREE.MeshStandardMaterial({color:0x303638,roughness:.92}),glass:new THREE.MeshPhysicalMaterial({color:0x608f99,metalness:.3,roughness:.17,clearcoat:.3}),stone:new THREE.MeshStandardMaterial({color:0xbdb5a3,roughness:.72}),dark:new THREE.MeshStandardMaterial({color:0x394541,metalness:.32,roughness:.55}),green:new THREE.MeshStandardMaterial({color:0x4c704d})};
function mesh(g,m,p=[0,0,0]){let o=new THREE.Mesh(g,m);o.position.set(...p);o.castShadow=o.receiveShadow=true;return o}let land=mesh(new THREE.PlaneGeometry(300,240),M.sand,[0,0,35]);land.rotation.x=-Math.PI/2;scene.add(land);let sea=mesh(new THREE.PlaneGeometry(320,140,50,25),new THREE.MeshPhysicalMaterial({color:0x096b8b,roughness:.12,metalness:.1,transparent:true,opacity:.93}),[0,-.18,-135]);sea.rotation.x=-Math.PI/2;scene.add(sea);let beach=mesh(new THREE.BoxGeometry(280,.15,8),new THREE.MeshStandardMaterial({color:0xe0c38d}),[0,.04,-68]);scene.add(beach);
function road(x,z,w,d){scene.add(mesh(new THREE.BoxGeometry(w,.1,d),M.road,[x,.05,z]))}[-90,-55,-20,18,58,95].forEach(x=>road(x,15,5,130));[-48,-24,5,37,67].forEach(z=>road(0,z,245,5));
const buildings=[];function tower(x,z,w,d,h,t=0){let g=new THREE.Group(),body;if(t===1)body=mesh(new THREE.CylinderGeometry(w*.42,w*.55,h,12),M.glass,[0,h/2,0]);else if(t===2){body=new THREE.Group();for(let i=0;i<4;i++){let hh=h/4+2,part=mesh(new THREE.BoxGeometry(w-i*.7,hh,d-i*.5),i%2?M.glass:M.stone,[0,hh/2+i*h/4,0]);part.rotation.y=i*.09;body.add(part)}}else if(t===3){body=mesh(new THREE.CylinderGeometry(w*.35,w*.52,h,18),M.glass,[0,h/2,0]);body.scale.x=.72;let sp=mesh(new THREE.ConeGeometry(.25,8,8),M.dark,[0,h+4,0]);g.add(sp)}else body=mesh(new THREE.BoxGeometry(w,h,d),t===4?M.glass:M.stone,[0,h/2,0]);g.add(body);g.add(mesh(new THREE.BoxGeometry(w*1.18,.8,d*1.18),M.dark,[0,.4,0]));g.position.set(x,0,z);scene.add(g);buildings.push(g);return g}
for(let i=0;i<150;i++){let x=-116+Math.random()*232,z=-42+Math.random()*118;if(Math.abs(x%38)<5||Math.abs(z-5)<5||Math.abs(z-37)<5)continue;let dt=Math.abs(x)<42&&z>2&&z<58;tower(x,z,3+Math.random()*7,3+Math.random()*7,dt?10+Math.random()*40:4+Math.random()*13,dt?Math.floor(Math.random()*5):0)}tower(-20,24,11,9,54,3);tower(0,29,14,11,45,2);tower(20,22,10,9,49,1);tower(36,30,9,9,36,4);
for(let i=0;i<42;i++)tower(-115+(i%21)*11,76+Math.floor(i/21)*11,6.5,6.5,4+Math.random()*3,0);
let park=mesh(new THREE.BoxGeometry(34,.14,21),M.green,[-62,.08,19]);scene.add(park);for(let i=0;i<28;i++){let x=-77+Math.random()*29,z=10+Math.random()*18;scene.add(mesh(new THREE.CylinderGeometry(.13,.22,2,7),M.dark,[x,1,z]));scene.add(mesh(new THREE.SphereGeometry(.75,7,6),M.green,[x,2.3,z]))}
for(let i=0;i<9;i++){scene.add(mesh(new THREE.BoxGeometry(2,.2,25),M.dark,[-100+i*25,.05,-81]));for(let j=0;j<4;j++)scene.add(mesh(new THREE.BoxGeometry(2.6,.55,5),new THREE.MeshStandardMaterial({color:0xe5e7e2}),[-94+i*25,.22,-75-j*6]))}
function radar(){let g=new THREE.Group();g.add(mesh(new THREE.CylinderGeometry(3.5,4.2,1,16),M.dark,[0,.5,0]));g.add(mesh(new THREE.CylinderGeometry(.3,.5,11,10),M.dark,[0,6,0]));let d=mesh(new THREE.SphereGeometry(2.8,20,12,0,Math.PI*2,0,Math.PI/2),new THREE.MeshStandardMaterial({color:0xc8cec5,metalness:.6,side:THREE.DoubleSide}),[0,11,0]);d.scale.z=.18;d.rotation.x=Math.PI/2;d.name='dish';g.add(d);g.position.set(-106,0,58);scene.add(g);return g}const radarSite=radar();
function launcher(){let g=new THREE.Group();g.add(mesh(new THREE.BoxGeometry(10,1.3,4.3),new THREE.MeshStandardMaterial({color:0x4c5849}),[0,1.2,0]));for(let x of[-3.4,-1.2,1.2,3.4])for(let z of[-1.8,1.8]){let w=mesh(new THREE.CylinderGeometry(.58,.58,.4,16),new THREE.MeshStandardMaterial({color:0x151815}),[x,.6,z]);w.rotation.z=Math.PI/2;g.add(w)}let rack=new THREE.Group();for(let r=0;r<4;r++)for(let c=0;c<4;c++)rack.add(mesh(new THREE.BoxGeometry(.76,6.3,.76),new THREE.MeshStandardMaterial({color:0x66705d}),[(c-1.5)*.85,(r-1.5)*.06,(r-1.5)*.85]));rack.rotation.x=-.9;rack.position.y=5.2;g.add(rack);g.position.set(98,0,57);g.rotation.y=-.7;scene.add(g);return g}const battery=launcher();
function interceptor(){let g=new THREE.Group(),white=new THREE.MeshStandardMaterial({color:0xebe9df,metalness:.25,roughness:.3});g.add(mesh(new THREE.CylinderGeometry(.13,.17,4.4,16),white));g.add(mesh(new THREE.ConeGeometry(.13,.9,16),white,[0,2.65,0]));g.add(mesh(new THREE.CylinderGeometry(.175,.175,.3,16),M.dark,[0,-1.2,0]));for(let i=0;i<4;i++){let f=mesh(new THREE.BoxGeometry(.65,.75,.05),M.dark,[0,-1.82,0]);f.rotation.y=i*Math.PI/2;g.add(f)}return g}function ballistic(heavy=false){let g=new THREE.Group(),m=new THREE.MeshStandardMaterial({color:heavy?0x929995:0xc9c4b7,metalness:.3,roughness:.4});g.add(mesh(new THREE.CylinderGeometry(.27,.4,6.2,16),m));g.add(mesh(new THREE.ConeGeometry(.27,1.6,16),m,[0,3.9,0]));g.add(mesh(new THREE.CylinderGeometry(.41,.41,.35,16),M.dark,[0,-1.5,0]));for(let i=0;i<4;i++){let f=mesh(new THREE.BoxGeometry(.07,1.3,1.25),m,[0,-2.5,0]);f.rotation.y=i*Math.PI/2;g.add(f)}g.scale.setScalar(heavy?1.4:1);return g}
const threats=[],ints=[],fx=[];let running=false,score=0,wave=1,hp=100,ammo=24,selected=null,spawn=0,next=1200,night=false,camMode=0;function orient(o,v){o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),v.clone().normalize())}function ui(){ $('#score').textContent=score;$('#wave').textContent=wave;$('#tracks').textContent=threats.length;$('#hp').textContent=Math.round(hp)+'%';$('#hpbar').style.width=hp+'%';$('#lock').textContent=selected?'LOCK T-'+selected.id+' // '+selected.kind:'NO TARGET LOCK';$('#fire').disabled=!running||!selected||ammo<=0}
function spawnThreat(){let heavy=wave>2&&Math.random()<.17,o=ballistic(heavy);o.position.set((Math.random()-.5)*170,70+Math.random()*28,-125);scene.add(o);let t={o,id:Math.floor(100+Math.random()*899),kind:heavy?'HEAVY':Math.random()<.28?'MANEUVER':'BALLISTIC',hp:heavy?3:1,v:new THREE.Vector3(),age:0,target:new THREE.Vector3((Math.random()-.5)*85,.2,-8+Math.random()*78)};o.userData.t=t;threats.push(t)}function blast(p,good){let o=mesh(new THREE.SphereGeometry(1,18,12),new THREE.MeshBasicMaterial({color:good?0x8deaff:0xff7048,transparent:true,opacity:.9}),[p.x,p.y,p.z]);scene.add(o);fx.push({o,t:0})}function destroy(t){blast(t.o.position,true);scene.remove(t.o);threats.splice(threats.indexOf(t),1);score+=t.kind==='HEAVY'?500:180;if(selected===t)selected=null;if(score>=next){wave++;next+=1200+wave*260;ammo+=5}ui()}
function fire(){if(!running||!selected||ammo<=0)return;ammo--;let o=interceptor();o.position.copy(battery.position).add(new THREE.Vector3(0,4,0));scene.add(o);ints.push({o,target:selected,v:new THREE.Vector3(0,11,-3)})}
function update(dt,now){if(!running)return;spawn-=dt;if(spawn<=0){spawnThreat();if(wave>4&&Math.random()<.24)spawnThreat();spawn=Math.max(.7,2.5-wave*.1)+Math.random()*.8}threats.slice().forEach(t=>{t.age+=dt;let d=t.target.clone().sub(t.o.position).normalize();if(t.kind==='MANEUVER')d.x+=Math.sin(t.age*2.1)*.035;t.v.lerp(d.multiplyScalar(t.kind==='HEAVY'?6.1:7.5),Math.min(1,dt*1.8));t.o.position.addScaledVector(t.v,dt);orient(t.o,t.v);if(t.o.position.y<.7){blast(t.o.position,false);scene.remove(t.o);threats.splice(threats.indexOf(t),1);hp=Math.max(0,hp-(t.kind==='HEAVY'?30:16));buildings.filter(b=>b.visible).sort(()=>Math.random()-.5).slice(0,t.kind==='HEAVY'?8:4).forEach(b=>b.visible=false);selected=null;if(hp<=0)running=false}});ints.slice().forEach(m=>{if(!threats.includes(m.target)){scene.remove(m.o);ints.splice(ints.indexOf(m),1);return}let d=m.target.o.position.clone().sub(m.o.position).normalize().multiplyScalar(20);m.v.lerp(d,Math.min(1,dt*2.7));m.o.position.addScaledVector(m.v,dt);orient(m.o,m.v);if(m.o.position.distanceTo(m.target.o.position)<2.7){blast(m.o.position,true);scene.remove(m.o);ints.splice(ints.indexOf(m),1);if(--m.target.hp<=0)destroy(m.target)}});fx.slice().forEach(f=>{f.t+=dt;f.o.scale.setScalar(1+f.t*10);f.o.material.opacity=1-f.t*1.5;if(f.t>.7){scene.remove(f.o);fx.splice(fx.indexOf(f),1)}});radarSite.getObjectByName('dish').rotation.z+=dt*1.8;let a=sea.geometry.attributes.position;for(let i=0;i<a.count;i++)a.setZ(i,Math.sin(a.getX(i)*.1+now*.0013)*.28+Math.cos(a.getY(i)*.12+now*.001)*.16);a.needsUpdate=true;ui()}
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();renderer.domElement.addEventListener('pointerup',e=>{let r=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);let h=ray.intersectObjects(threats.map(t=>t.o),true);if(h.length){let o=h[0].object;while(o&&!o.userData.t)o=o.parent;if(o){selected=o.userData.t;ui()}}});$('#start').onclick=()=>{threats.splice(0).forEach(t=>scene.remove(t.o));ints.splice(0).forEach(m=>scene.remove(m.o));buildings.forEach(b=>b.visible=true);running=true;score=0;wave=1;hp=100;ammo=24;spawn=.2;next=1200;selected=null;ui()};$('#fire').onclick=fire;$('#cam').onclick=()=>{camMode=(camMode+1)%4;if(camMode===0){camera.position.set(92,64,126);controls.target.set(0,10,5)}if(camMode===1){camera.position.set(115,18,78);controls.target.copy(battery.position)}if(camMode===2){camera.position.set(-88,28,80);controls.target.copy(radarSite.position)}if(camMode===3&&selected){camera.position.copy(selected.o.position).add(new THREE.Vector3(18,9,25));controls.target.copy(selected.o.position)}};$('#night').onclick=()=>{night=!night;scene.background.set(night?0x020713:0x78aebe);scene.fog.color.set(night?0x07111a:0x86aeb3);sun.intensity=night?.35:3.6};$('#repair').onclick=()=>{if(!running)return;hp=Math.min(100,hp+20);buildings.filter(b=>!b.visible).slice(0,10).forEach(b=>b.visible=true);ui()};$('#supply').onclick=()=>{if(running)ammo+=8};addEventListener('keydown',e=>{if(e.code==='Space')fire()});addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
let last=performance.now();function loop(now){let dt=Math.min(.035,(now-last)/1000);last=now;update(dt,now);if(camMode===3&&selected){controls.target.lerp(selected.o.position,.12)}controls.update();renderer.render(scene,camera);requestAnimationFrame(loop)}$('#boot').style.display='none';ui();requestAnimationFrame(loop);
